// <auto-generated />
using HeThongQuanLyCongTacKhaoThi.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HeThongQuanLyCongTacKhaoThi.Data.Migrations
{
    [DbContext(typeof(HeThongQuanLyCongTacKhaoThiDbContext))]
    [Migration("20201106101344_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Answer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .IsUnicode(true);

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("QuestionID");

                    b.ToTable("ANSWER");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Class", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .IsUnicode(true);

                    b.Property<int>("StudentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ID");

                    b.ToTable("CLASS");

                    b.HasData(
                        new
                        {
                            ID = "DHCN1A",
                            Name = "Đại học công nghệ 1A",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN1B",
                            Name = "Đại học công nghệ 1B",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN1C",
                            Name = "Đại học công nghệ 1C",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN1D",
                            Name = "Đại học công nghệ 1D",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN2A",
                            Name = "Đại học công nghệ 2A",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN2B",
                            Name = "Đại học công nghệ 2B",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN3A",
                            Name = "Đại học công nghệ 3A",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN3B",
                            Name = "Đại học công nghệ 3B",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN3C",
                            Name = "Đại học công nghệ 3C",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN4A",
                            Name = "Đại học công nghệ 4A",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN4B",
                            Name = "Đại học công nghệ 4B",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHVT1",
                            Name = "Đại học viễn thông 1",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHVT2",
                            Name = "Đại học viễn thông 2",
                            StudentCount = 0
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Exam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .IsUnicode(true);

                    b.HasKey("ID");

                    b.ToTable("EXAM");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.ExamDetail", b =>
                {
                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("ExamID", "QuestionID");

                    b.HasIndex("QuestionID");

                    b.ToTable("EXAM_DETAIL");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .IsUnicode(true);

                    b.Property<bool>("IsMultipleChoice")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("SubjectID");

                    b.ToTable("QUESTION");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Result", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<float>("Mark")
                        .HasColumnType("real");

                    b.Property<int>("ScoreID")
                        .HasColumnType("int");

                    b.Property<int>("StudentAnswerID")
                        .HasColumnType("int");

                    b.Property<string>("SubjectID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ExamID");

                    b.HasIndex("ScoreID");

                    b.HasIndex("StudentAnswerID");

                    b.HasIndex("SubjectID");

                    b.ToTable("RESULT");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Score", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .IsUnicode(true);

                    b.HasKey("ID");

                    b.ToTable("SCORE");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Điểm chuyên cần"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Điểm thường xuyên"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Điểm giữa môn"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Điểm kết thúc môn"
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ExamID");

                    b.ToTable("STUDENT_ANSWER");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswerDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnswerID")
                        .HasColumnType("int");

                    b.Property<string>("EssayPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("StudentAnswerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AnswerID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("StudentAnswerID");

                    b.ToTable("STUDENT_ANSWER_DETAIL");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("AssiduousScorePercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0.1f);

                    b.Property<int>("CreditCount")
                        .HasColumnType("int");

                    b.Property<float>("FinalScorePercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0.5f);

                    b.Property<float>("FrequentScorePercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0.2f);

                    b.Property<float>("MiddleScorePercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0.2f);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .IsUnicode(true);

                    b.HasKey("ID");

                    b.ToTable("SUBJECT");

                    b.HasData(
                        new
                        {
                            ID = "CC4206",
                            AssiduousScorePercent = 0f,
                            CreditCount = 3,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Nhập môn lập trình"
                        },
                        new
                        {
                            ID = "DH4202",
                            AssiduousScorePercent = 0f,
                            CreditCount = 3,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Kỹ thuật lập trình"
                        },
                        new
                        {
                            ID = "DH4203",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Cấu trúc dữ liệu & giải thuật"
                        },
                        new
                        {
                            ID = "TC4209",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Lập trình hướng đối tượng"
                        },
                        new
                        {
                            ID = "DC4204",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            ID = "DC4106",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Kiến trúc máy tính"
                        },
                        new
                        {
                            ID = "DT4208",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Lập trình Java"
                        },
                        new
                        {
                            ID = "DT4315",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Công nghệ phần mềm"
                        },
                        new
                        {
                            ID = "DT4205",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "SQL Server"
                        },
                        new
                        {
                            ID = "DT4301",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Mạng máy tính"
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Answer", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.ExamDetail", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Exam", "Exam")
                        .WithMany("ExamDetails")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", "Question")
                        .WithMany("ExamDetails")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", "Subject")
                        .WithMany("Questions")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Result", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Exam", "Exam")
                        .WithMany("Results")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Score", "Score")
                        .WithMany("Results")
                        .HasForeignKey("ScoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswer", "StudentAnswer")
                        .WithMany("Results")
                        .HasForeignKey("StudentAnswerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", "Subject")
                        .WithMany("Results")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswer", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Exam", "Exam")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswerDetail", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Answer", "Answer")
                        .WithMany("StudentAnswerDetails")
                        .HasForeignKey("AnswerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", "Question")
                        .WithMany("StudentAnswerDetails")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswer", "StudentAnswer")
                        .WithMany("StudentAnswerDetails")
                        .HasForeignKey("StudentAnswerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
