// <auto-generated />
using System;
using HeThongQuanLyCongTacKhaoThi.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HeThongQuanLyCongTacKhaoThi.Data.Migrations
{
    [DbContext(typeof(HeThongQuanLyCongTacKhaoThiDbContext))]
    [Migration("20201109091629_AspNetCoreIdentityDatabase")]
    partial class AspNetCoreIdentityDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(true);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_TeacherID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassID");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("efe5c78c-bbc5-40e5-a106-1f07d4b4fcdb"),
                            AccessFailedCount = 0,
                            Birthday = new DateTime(1999, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "5bebaa42-d9ec-437c-8df0-3a1ddaf7b484",
                            Email = "keycodemon@gmail.com",
                            EmailConfirmed = true,
                            Gender = true,
                            LockoutEnabled = false,
                            Name = "Keycode Mon",
                            NormalizedEmail = "keycodemon@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEGiqIB+QVWW41PFjxVzZsOVdT5cnv+hggGGwXn8j/RAgQ+qunI3YQDCJ2BK/SFzNiw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Answer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .IsUnicode(true);

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("QuestionID");

                    b.ToTable("ANSWER");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Class", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<int>("StudentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ID");

                    b.ToTable("CLASS");

                    b.HasData(
                        new
                        {
                            ID = "DHCN1A",
                            Name = "Đại học công nghệ 1A",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN1B",
                            Name = "Đại học công nghệ 1B",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN1C",
                            Name = "Đại học công nghệ 1C",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN1D",
                            Name = "Đại học công nghệ 1D",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN2A",
                            Name = "Đại học công nghệ 2A",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN2B",
                            Name = "Đại học công nghệ 2B",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN3A",
                            Name = "Đại học công nghệ 3A",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN3B",
                            Name = "Đại học công nghệ 3B",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN3C",
                            Name = "Đại học công nghệ 3C",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN4A",
                            Name = "Đại học công nghệ 4A",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN4B",
                            Name = "Đại học công nghệ 4B",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHVT1",
                            Name = "Đại học viễn thông 1",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHVT2",
                            Name = "Đại học viễn thông 2",
                            StudentCount = 0
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Exam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.HasKey("ID");

                    b.ToTable("EXAM");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.ExamDetail", b =>
                {
                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("ExamID", "QuestionID");

                    b.HasIndex("QuestionID");

                    b.ToTable("EXAM_DETAIL");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .IsUnicode(true);

                    b.Property<bool>("IsMultipleChoice")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ID");

                    b.HasIndex("SubjectID");

                    b.ToTable("QUESTION");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Result", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<float>("Mark")
                        .HasColumnType("real");

                    b.Property<int>("ScoreID")
                        .HasColumnType("int");

                    b.Property<int>("StudentAnswerID")
                        .HasColumnType("int");

                    b.Property<string>("SubjectID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ExamID");

                    b.HasIndex("ScoreID");

                    b.HasIndex("StudentAnswerID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("UserID");

                    b.ToTable("RESULT");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.RoleAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(true);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleAccount");

                    b.HasData(
                        new
                        {
                            Id = new Guid("efe5c78c-bbc5-40e5-a106-1f07d4b4fcdb"),
                            ConcurrencyStamp = "84fe7a07-bf7b-48e7-8e6b-782c9c294b2c",
                            Description = "Vai trò quản trị viên",
                            Name = "admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Score", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(true);

                    b.HasKey("ID");

                    b.ToTable("SCORE");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Điểm chuyên cần"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Điểm thường xuyên"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Điểm giữa môn"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Điểm kết thúc môn"
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ExamID");

                    b.HasIndex("UserID");

                    b.ToTable("STUDENT_ANSWER");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswerDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnswerID")
                        .HasColumnType("int");

                    b.Property<string>("EssayPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("StudentAnswerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AnswerID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("StudentAnswerID");

                    b.ToTable("STUDENT_ANSWER_DETAIL");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<float>("AssiduousScorePercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0.1f);

                    b.Property<int>("CreditCount")
                        .HasColumnType("int");

                    b.Property<float>("FinalScorePercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0.5f);

                    b.Property<float>("FrequentScorePercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0.2f);

                    b.Property<float>("MiddleScorePercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0.2f);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.HasKey("ID");

                    b.ToTable("SUBJECT");

                    b.HasData(
                        new
                        {
                            ID = "CC4206",
                            AssiduousScorePercent = 0f,
                            CreditCount = 3,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Nhập môn lập trình"
                        },
                        new
                        {
                            ID = "DH4202",
                            AssiduousScorePercent = 0f,
                            CreditCount = 3,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Kỹ thuật lập trình"
                        },
                        new
                        {
                            ID = "DH4203",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Cấu trúc dữ liệu & giải thuật"
                        },
                        new
                        {
                            ID = "TC4209",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Lập trình hướng đối tượng"
                        },
                        new
                        {
                            ID = "DC4204",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            ID = "DC4106",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Kiến trúc máy tính"
                        },
                        new
                        {
                            ID = "DT4208",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Lập trình Java"
                        },
                        new
                        {
                            ID = "DT4315",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Công nghệ phần mềm"
                        },
                        new
                        {
                            ID = "DT4205",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "SQL Server"
                        },
                        new
                        {
                            ID = "DT4301",
                            AssiduousScorePercent = 0f,
                            CreditCount = 4,
                            FinalScorePercent = 0f,
                            FrequentScorePercent = 0f,
                            MiddleScorePercent = 0f,
                            Name = "Mạng máy tính"
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.SubjectTeacher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SubjectID")
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AccountId");

                    b.HasIndex("ClassID");

                    b.HasIndex("SubjectID");

                    b.ToTable("SubjectTeacher");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ROLE_CLAIM");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("USER_CLAIM");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("USER_LOGIN");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("USER_ROLE");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("efe5c78c-bbc5-40e5-a106-1f07d4b4fcdb"),
                            RoleId = new Guid("efe5c78c-bbc5-40e5-a106-1f07d4b4fcdb")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("USER_TOKEN");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Account", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Class", "Class")
                        .WithMany("Accounts")
                        .HasForeignKey("ClassID");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Answer", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.ExamDetail", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Exam", "Exam")
                        .WithMany("ExamDetails")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", "Question")
                        .WithMany("ExamDetails")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", "Subject")
                        .WithMany("Questions")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Result", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Exam", "Exam")
                        .WithMany("Results")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Score", "Score")
                        .WithMany("Results")
                        .HasForeignKey("ScoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswer", "StudentAnswer")
                        .WithMany("Results")
                        .HasForeignKey("StudentAnswerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", "Subject")
                        .WithMany("Results")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Account", "Account")
                        .WithMany("Results")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswer", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Exam", "Exam")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Account", "Account")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswerDetail", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Answer", "Answer")
                        .WithMany("StudentAnswerDetails")
                        .HasForeignKey("AnswerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", "Question")
                        .WithMany("StudentAnswerDetails")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswer", "StudentAnswer")
                        .WithMany("StudentAnswerDetails")
                        .HasForeignKey("StudentAnswerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.SubjectTeacher", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Account", "Account")
                        .WithMany("SubjectTeachers")
                        .HasForeignKey("AccountId");

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Class", "Class")
                        .WithMany("SubjectTeachers")
                        .HasForeignKey("ClassID");

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", "Subject")
                        .WithMany("SubjectTeachers")
                        .HasForeignKey("SubjectID");
                });
#pragma warning restore 612, 618
        }
    }
}
