// <auto-generated />
using System;
using HeThongQuanLyCongTacKhaoThi.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HeThongQuanLyCongTacKhaoThi.Data.Migrations
{
    [DbContext(typeof(HeThongQuanLyCongTacKhaoThiDbContext))]
    partial class HeThongQuanLyCongTacKhaoThiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(true);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_TeacherID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassID");

                    b.ToTable("ACCOUNT");

                    b.HasData(
                        new
                        {
                            Id = new Guid("efe5c78c-bbc5-40e5-a106-1f07d4b4fcdb"),
                            AccessFailedCount = 0,
                            Birthday = new DateTime(1999, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "80cfa4eb-9745-47a3-8b0c-aded87136bf0",
                            Email = "keycodemon@gmail.com",
                            EmailConfirmed = true,
                            Gender = true,
                            LockoutEnabled = false,
                            Name = "Keycode Mon",
                            NormalizedEmail = "keycodemon@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAENoV+l0pWD/kzjBPI3Bptz2/OAYpPAKV4EvUqDcbe0OfBHxL9H0iZryBhMJvOvSyJw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("4a2d9b6e-97c4-41bd-a929-f778972db109"),
                            AccessFailedCount = 0,
                            Address = "Số 80 - Hai Bà Trưng - Vạn Giã - Vạn Ninh - Khánh Hoà",
                            Birthday = new DateTime(1999, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = "DHCN4A",
                            ConcurrencyStamp = "9f5c8e36-62c2-4cae-8afd-9e8a925c8667",
                            Email = "htthinh1999@gmail.com",
                            EmailConfirmed = true,
                            Gender = true,
                            LockoutEnabled = false,
                            Name = "Huỳnh Tấn Thịnh",
                            NormalizedEmail = "htthinh1999@gmail.com",
                            NormalizedUserName = "htthinh",
                            PasswordHash = "AQAAAAEAACcQAAAAEI8JE49PXqxFg6s5OMhnFZAuZVtx8fpFyjDG9dKxtzEgWM8pkDG8CIS6M6AJTwbdig==",
                            PhoneNumber = "0977393641",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            Student_TeacherID = "17ĐC027",
                            TwoFactorEnabled = false,
                            UserName = "htthinh"
                        },
                        new
                        {
                            Id = new Guid("9e7773ef-083c-4a8e-8ed2-9e36cd704913"),
                            AccessFailedCount = 0,
                            Address = "Khánh Hoà",
                            Birthday = new DateTime(2000, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = "DHCN4A",
                            ConcurrencyStamp = "e8fe953c-1ef0-4e6c-8324-dbfd2ee46010",
                            Email = "sv1@gmail.com",
                            EmailConfirmed = true,
                            Gender = true,
                            LockoutEnabled = false,
                            Name = "Sinh viên 1",
                            NormalizedEmail = "sv1@gmail.com",
                            NormalizedUserName = "sv1",
                            PasswordHash = "AQAAAAEAACcQAAAAEOgRXVCrX7tWPeVkraM9IQ8bWsNi354265WFEbvugzSIeDZvCf/vUSME0lCZ3sZbQQ==",
                            PhoneNumber = "0987333644",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            Student_TeacherID = "17ĐC028",
                            TwoFactorEnabled = false,
                            UserName = "sv1"
                        },
                        new
                        {
                            Id = new Guid("8bc30f33-6382-45fd-a54a-0dec677631d9"),
                            AccessFailedCount = 0,
                            Address = "Khánh Hoà",
                            Birthday = new DateTime(2000, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = "DHCN4A",
                            ConcurrencyStamp = "e339e03b-89fb-49ad-be79-3c9ac501fbe4",
                            Email = "sv2@gmail.com",
                            EmailConfirmed = true,
                            Gender = true,
                            LockoutEnabled = false,
                            Name = "Sinh viên 2",
                            NormalizedEmail = "sv2@gmail.com",
                            NormalizedUserName = "sv2",
                            PasswordHash = "AQAAAAEAACcQAAAAEC0oJfblAcM4tXspBOVuw8WZZlZjH2lf6skxuYofqzfC49Ox62R7IPKqfz5HXOQ4Ww==",
                            PhoneNumber = "0987666644",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            Student_TeacherID = "17ĐC023",
                            TwoFactorEnabled = false,
                            UserName = "sv2"
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Answer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .IsUnicode(true);

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("QuestionID");

                    b.ToTable("ANSWER");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Content = "diem toan",
                            IsCorrect = false,
                            QuestionID = 1
                        },
                        new
                        {
                            ID = 2,
                            Content = "3diemtoan",
                            IsCorrect = false,
                            QuestionID = 1
                        },
                        new
                        {
                            ID = 3,
                            Content = "_diemtoan",
                            IsCorrect = true,
                            QuestionID = 1
                        },
                        new
                        {
                            ID = 4,
                            Content = "-diemtoan",
                            IsCorrect = false,
                            QuestionID = 1
                        },
                        new
                        {
                            ID = 5,
                            Content = "Nó được khai báo tất cả các hàm, ngoại trừ hàm main()",
                            IsCorrect = false,
                            QuestionID = 2
                        },
                        new
                        {
                            ID = 6,
                            Content = "Nó được khai báo ngoài tất cả các hàm kể cả hàm main()",
                            IsCorrect = true,
                            QuestionID = 2
                        },
                        new
                        {
                            ID = 7,
                            Content = "Nó được khai báo bên ngoài hàm main()",
                            IsCorrect = false,
                            QuestionID = 2
                        },
                        new
                        {
                            ID = 8,
                            Content = "Nó được khai báo bên trong hàm main()",
                            IsCorrect = false,
                            QuestionID = 2
                        },
                        new
                        {
                            ID = 9,
                            Content = "Nó được khai báo bên trong các hàm hoặc thủ tục, kể cả hàm main()",
                            IsCorrect = true,
                            QuestionID = 3
                        },
                        new
                        {
                            ID = 10,
                            Content = "Nó được khai báo bên trong các hàm ngoại trừ hàm main()",
                            IsCorrect = false,
                            QuestionID = 3
                        },
                        new
                        {
                            ID = 11,
                            Content = "Nó được khai báo bên trong hàm main()",
                            IsCorrect = false,
                            QuestionID = 3
                        },
                        new
                        {
                            ID = 12,
                            Content = "Nó được khai báo bên ngoài các hàm kể cả hàm main()",
                            IsCorrect = false,
                            QuestionID = 3
                        },
                        new
                        {
                            ID = 13,
                            Content = "Đệ quy khiến chương trình bị treo.",
                            IsCorrect = false,
                            QuestionID = 4
                        },
                        new
                        {
                            ID = 14,
                            Content = "Đệ quy vô hạn tiêu tốn toàn bộ bộ nhớ của hệ thống dành cho chương trình và khiến cho chương trình kết thúc một cách bất thường.",
                            IsCorrect = false,
                            QuestionID = 4
                        },
                        new
                        {
                            ID = 15,
                            Content = "	Gọi đệ quy gián tiếp luôn gây ra đệ quy vô hạn.",
                            IsCorrect = true,
                            QuestionID = 4
                        },
                        new
                        {
                            ID = 16,
                            Content = "Nếu lời gọi đệ quy không đi đến điểm dừng (base case) thì đệ quy vô hạn sẽ xuất hiện.",
                            IsCorrect = false,
                            QuestionID = 4
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Class", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<int>("StudentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ID");

                    b.ToTable("CLASS");

                    b.HasData(
                        new
                        {
                            ID = "DHCN1A",
                            Name = "Đại học công nghệ 1A",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN1B",
                            Name = "Đại học công nghệ 1B",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN1C",
                            Name = "Đại học công nghệ 1C",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN1D",
                            Name = "Đại học công nghệ 1D",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN2A",
                            Name = "Đại học công nghệ 2A",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN2B",
                            Name = "Đại học công nghệ 2B",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN3A",
                            Name = "Đại học công nghệ 3A",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN3B",
                            Name = "Đại học công nghệ 3B",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN3C",
                            Name = "Đại học công nghệ 3C",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN4A",
                            Name = "Đại học công nghệ 4A",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHCN4B",
                            Name = "Đại học công nghệ 4B",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHVT1",
                            Name = "Đại học viễn thông 1",
                            StudentCount = 0
                        },
                        new
                        {
                            ID = "DHVT2",
                            Name = "Đại học viễn thông 2",
                            StudentCount = 0
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Contest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<int>("ScoreTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("ScoreTypeID");

                    b.HasIndex("SubjectID");

                    b.ToTable("CONTEST");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Exam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContestID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(true);

                    b.Property<string>("SubjectID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ID");

                    b.HasIndex("ContestID");

                    b.HasIndex("SubjectID");

                    b.ToTable("EXAM");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.ExamDetail", b =>
                {
                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<float>("MaxQuestionMark")
                        .HasColumnType("real");

                    b.HasKey("ExamID", "QuestionID");

                    b.HasIndex("QuestionID");

                    b.ToTable("EXAM_DETAIL");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Notification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<Guid>("StudentAnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<string>("SubjectID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("StudentAnswerID");

                    b.HasIndex("SubjectID");

                    b.ToTable("NOTIFICATION");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .IsUnicode(true);

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<bool>("IsMultipleChoice")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ID");

                    b.HasIndex("GroupID");

                    b.HasIndex("SubjectID");

                    b.ToTable("QUESTION");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Content = "Những tên biến nào dưới đây được viết đúng theo quy tắc đặt tên của ngôn ngữ lập trình C?",
                            GroupID = 1,
                            IsMultipleChoice = true,
                            SubjectID = "CC4206"
                        },
                        new
                        {
                            ID = 2,
                            Content = "Một biến được gọi là biến toàn cục nếu:",
                            GroupID = 1,
                            IsMultipleChoice = true,
                            SubjectID = "CC4206"
                        },
                        new
                        {
                            ID = 3,
                            Content = "Một biến được gọi là biến cục bộ nếu:",
                            GroupID = 1,
                            IsMultipleChoice = true,
                            SubjectID = "CC4206"
                        },
                        new
                        {
                            ID = 4,
                            Content = "Nhận định nào sau đây KHÔNG ĐÚNG về đệ quy vô hạn?",
                            GroupID = 2,
                            IsMultipleChoice = true,
                            SubjectID = "CC4206"
                        },
                        new
                        {
                            ID = 5,
                            Content = "Trong các phương pháp sắp xếp: lựa chọn, chèn, đổi chỗ(nổi bọt), quicksort (sắp xếp nhanh), mergesort (sắp xếp trộn), thì phương pháp nào là phù hợp nhất để sắp xếp trên danh sách liên kết đơn ? Giải thích ? ",
                            GroupID = 2,
                            IsMultipleChoice = false,
                            SubjectID = "CC4206"
                        },
                        new
                        {
                            ID = 6,
                            Content = "Trình bày sự khác biệt giữa mảng cấp phát bộ nhớ động và mảng cấp phát tĩnh? Khi nào dùng mảng cấp phát động, mảng cấp phát tĩnh ? Cho ví dụ ?",
                            GroupID = 2,
                            IsMultipleChoice = false,
                            SubjectID = "CC4206"
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.QuestionGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("QUESTION_GROUP");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Nhóm câu hỏi chương 1"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Nhóm câu hỏi chương 2"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Nhóm câu hỏi chương 3"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Nhóm câu hỏi chương 4"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Nhóm câu hỏi chương 5"
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Result", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContestID")
                        .HasColumnType("int");

                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<float>("Mark")
                        .HasColumnType("real");

                    b.Property<Guid>("StudentAnswerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubjectID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ContestID");

                    b.HasIndex("ExamID");

                    b.HasIndex("StudentAnswerID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("UserID");

                    b.ToTable("RESULT");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(true);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ROLE");

                    b.HasData(
                        new
                        {
                            Id = new Guid("61a4fad5-402c-4ce0-845d-1fbd2b91956f"),
                            ConcurrencyStamp = "f1db34f7-f762-4270-94fc-0324dc216cf2",
                            Description = "Vai trò quản trị viên",
                            Name = "Admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = new Guid("1e6d489f-1df4-4dab-b873-ce3224d87f94"),
                            ConcurrencyStamp = "3c6c4652-923c-45dc-afb2-3e817e93abfe",
                            Description = "Vai trò giảng viên",
                            Name = "Teacher",
                            NormalizedName = "teacher"
                        },
                        new
                        {
                            Id = new Guid("9a34bdd4-fa97-4e2f-9960-b19a68826be9"),
                            ConcurrencyStamp = "6a085597-60d8-492b-b804-4970d853c269",
                            Description = "Vai trò học viên",
                            Name = "Student",
                            NormalizedName = "student"
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.ScoreType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(true);

                    b.Property<float>("Percent")
                        .HasColumnType("real");

                    b.Property<string>("SubjectID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ID");

                    b.HasIndex("SubjectID");

                    b.ToTable("SCORE_TYPE");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Điểm chuyên cần",
                            Percent = 0.1f,
                            SubjectID = "CC4206"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Điểm thường xuyên",
                            Percent = 0.2f,
                            SubjectID = "CC4206"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Điểm giữa môn",
                            Percent = 0.2f,
                            SubjectID = "CC4206"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Điểm kết thúc môn",
                            Percent = 0.5f,
                            SubjectID = "CC4206"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Điểm chuyên cần",
                            Percent = 0.1f,
                            SubjectID = "DH4202"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Điểm thường xuyên",
                            Percent = 0.2f,
                            SubjectID = "DH4202"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Điểm giữa môn",
                            Percent = 0.2f,
                            SubjectID = "DH4202"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Điểm kết thúc môn",
                            Percent = 0.5f,
                            SubjectID = "DH4202"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Điểm chuyên cần",
                            Percent = 0.1f,
                            SubjectID = "DH4203"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Điểm thường xuyên",
                            Percent = 0.2f,
                            SubjectID = "DH4203"
                        },
                        new
                        {
                            ID = 11,
                            Name = "Điểm giữa môn",
                            Percent = 0.2f,
                            SubjectID = "DH4203"
                        },
                        new
                        {
                            ID = 12,
                            Name = "Điểm kết thúc môn",
                            Percent = 0.5f,
                            SubjectID = "DH4203"
                        },
                        new
                        {
                            ID = 13,
                            Name = "Điểm chuyên cần",
                            Percent = 0.1f,
                            SubjectID = "TC4209"
                        },
                        new
                        {
                            ID = 14,
                            Name = "Điểm thường xuyên",
                            Percent = 0.2f,
                            SubjectID = "TC4209"
                        },
                        new
                        {
                            ID = 15,
                            Name = "Điểm giữa môn",
                            Percent = 0.2f,
                            SubjectID = "TC4209"
                        },
                        new
                        {
                            ID = 16,
                            Name = "Điểm kết thúc môn",
                            Percent = 0.5f,
                            SubjectID = "TC4209"
                        },
                        new
                        {
                            ID = 17,
                            Name = "Điểm chuyên cần",
                            Percent = 0.1f,
                            SubjectID = "DC4204"
                        },
                        new
                        {
                            ID = 18,
                            Name = "Điểm thường xuyên",
                            Percent = 0.2f,
                            SubjectID = "DC4204"
                        },
                        new
                        {
                            ID = 19,
                            Name = "Điểm giữa môn",
                            Percent = 0.2f,
                            SubjectID = "DC4204"
                        },
                        new
                        {
                            ID = 20,
                            Name = "Điểm kết thúc môn",
                            Percent = 0.5f,
                            SubjectID = "DC4204"
                        },
                        new
                        {
                            ID = 21,
                            Name = "Điểm chuyên cần",
                            Percent = 0.1f,
                            SubjectID = "DC4106"
                        },
                        new
                        {
                            ID = 22,
                            Name = "Điểm thường xuyên",
                            Percent = 0.2f,
                            SubjectID = "DC4106"
                        },
                        new
                        {
                            ID = 23,
                            Name = "Điểm giữa môn",
                            Percent = 0.2f,
                            SubjectID = "DC4106"
                        },
                        new
                        {
                            ID = 24,
                            Name = "Điểm kết thúc môn",
                            Percent = 0.5f,
                            SubjectID = "DC4106"
                        },
                        new
                        {
                            ID = 25,
                            Name = "Điểm chuyên cần",
                            Percent = 0.1f,
                            SubjectID = "DT4208"
                        },
                        new
                        {
                            ID = 26,
                            Name = "Điểm thường xuyên",
                            Percent = 0.2f,
                            SubjectID = "DT4208"
                        },
                        new
                        {
                            ID = 27,
                            Name = "Điểm giữa môn",
                            Percent = 0.2f,
                            SubjectID = "DT4208"
                        },
                        new
                        {
                            ID = 28,
                            Name = "Điểm kết thúc môn",
                            Percent = 0.5f,
                            SubjectID = "DT4208"
                        },
                        new
                        {
                            ID = 29,
                            Name = "Điểm chuyên cần",
                            Percent = 0.1f,
                            SubjectID = "DT4315"
                        },
                        new
                        {
                            ID = 30,
                            Name = "Điểm thường xuyên",
                            Percent = 0.2f,
                            SubjectID = "DT4315"
                        },
                        new
                        {
                            ID = 31,
                            Name = "Điểm giữa môn",
                            Percent = 0.2f,
                            SubjectID = "DT4315"
                        },
                        new
                        {
                            ID = 32,
                            Name = "Điểm kết thúc môn",
                            Percent = 0.5f,
                            SubjectID = "DT4315"
                        },
                        new
                        {
                            ID = 33,
                            Name = "Điểm chuyên cần",
                            Percent = 0.1f,
                            SubjectID = "DT4205"
                        },
                        new
                        {
                            ID = 34,
                            Name = "Điểm thường xuyên",
                            Percent = 0.2f,
                            SubjectID = "DT4205"
                        },
                        new
                        {
                            ID = 35,
                            Name = "Điểm giữa môn",
                            Percent = 0.2f,
                            SubjectID = "DT4205"
                        },
                        new
                        {
                            ID = 36,
                            Name = "Điểm kết thúc môn",
                            Percent = 0.5f,
                            SubjectID = "DT4205"
                        },
                        new
                        {
                            ID = 37,
                            Name = "Điểm chuyên cần",
                            Percent = 0.1f,
                            SubjectID = "DT4301"
                        },
                        new
                        {
                            ID = 38,
                            Name = "Điểm thường xuyên",
                            Percent = 0.2f,
                            SubjectID = "DT4301"
                        },
                        new
                        {
                            ID = 39,
                            Name = "Điểm giữa môn",
                            Percent = 0.2f,
                            SubjectID = "DT4301"
                        },
                        new
                        {
                            ID = 40,
                            Name = "Điểm kết thúc môn",
                            Percent = 0.5f,
                            SubjectID = "DT4301"
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswer", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ExamID");

                    b.HasIndex("UserID");

                    b.ToTable("STUDENT_ANSWER");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswerDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(null);

                    b.Property<string>("EssayPath")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue(null);

                    b.Property<float?>("Mark")
                        .HasColumnType("real");

                    b.Property<float?>("Mark1")
                        .HasColumnType("real");

                    b.Property<float?>("Mark2")
                        .HasColumnType("real");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<string>("StudentAnswerContent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .IsUnicode(true)
                        .HasDefaultValue(null);

                    b.Property<Guid>("StudentAnswerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Teacher1Comment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Chưa có nhận xét!");

                    b.Property<string>("Teacher2Comment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Chưa có nhận xét!");

                    b.HasKey("ID");

                    b.HasIndex("AnswerID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("StudentAnswerID");

                    b.ToTable("STUDENT_ANSWER_DETAIL");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("CreditCount")
                        .HasColumnType("int");

                    b.Property<int>("LessonCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.HasKey("ID");

                    b.ToTable("SUBJECT");

                    b.HasData(
                        new
                        {
                            ID = "CC4206",
                            CreditCount = 3,
                            LessonCount = 45,
                            Name = "Nhập môn lập trình"
                        },
                        new
                        {
                            ID = "DH4202",
                            CreditCount = 3,
                            LessonCount = 45,
                            Name = "Kỹ thuật lập trình"
                        },
                        new
                        {
                            ID = "DH4203",
                            CreditCount = 4,
                            LessonCount = 45,
                            Name = "Cấu trúc dữ liệu & giải thuật"
                        },
                        new
                        {
                            ID = "TC4209",
                            CreditCount = 4,
                            LessonCount = 45,
                            Name = "Lập trình hướng đối tượng"
                        },
                        new
                        {
                            ID = "DC4204",
                            CreditCount = 4,
                            LessonCount = 45,
                            Name = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            ID = "DC4106",
                            CreditCount = 4,
                            LessonCount = 45,
                            Name = "Kiến trúc máy tính"
                        },
                        new
                        {
                            ID = "DT4208",
                            CreditCount = 4,
                            LessonCount = 45,
                            Name = "Lập trình Java"
                        },
                        new
                        {
                            ID = "DT4315",
                            CreditCount = 4,
                            LessonCount = 45,
                            Name = "Công nghệ phần mềm"
                        },
                        new
                        {
                            ID = "DT4205",
                            CreditCount = 4,
                            LessonCount = 45,
                            Name = "SQL Server"
                        },
                        new
                        {
                            ID = "DT4301",
                            CreditCount = 4,
                            LessonCount = 45,
                            Name = "Mạng máy tính"
                        });
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.SubjectAccount", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubjectID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("UserID", "SubjectID");

                    b.HasIndex("ClassID");

                    b.HasIndex("SubjectID");

                    b.ToTable("SUBJECT_ACCOUNT");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.TeacherContest", b =>
                {
                    b.Property<Guid>("TeacherID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContestID")
                        .HasColumnType("int");

                    b.HasKey("TeacherID", "ContestID");

                    b.HasIndex("ContestID");

                    b.ToTable("TEACHER_CONTEST");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ROLE_CLAIM");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("USER_CLAIM");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("USER_LOGIN");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("USER_ROLE");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("efe5c78c-bbc5-40e5-a106-1f07d4b4fcdb"),
                            RoleId = new Guid("61a4fad5-402c-4ce0-845d-1fbd2b91956f")
                        },
                        new
                        {
                            UserId = new Guid("4a2d9b6e-97c4-41bd-a929-f778972db109"),
                            RoleId = new Guid("1e6d489f-1df4-4dab-b873-ce3224d87f94")
                        },
                        new
                        {
                            UserId = new Guid("9e7773ef-083c-4a8e-8ed2-9e36cd704913"),
                            RoleId = new Guid("9a34bdd4-fa97-4e2f-9960-b19a68826be9")
                        },
                        new
                        {
                            UserId = new Guid("8bc30f33-6382-45fd-a54a-0dec677631d9"),
                            RoleId = new Guid("9a34bdd4-fa97-4e2f-9960-b19a68826be9")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("USER_TOKEN");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Account", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Class", "Class")
                        .WithMany("Accounts")
                        .HasForeignKey("ClassID");
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Answer", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Contest", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.ScoreType", "ScoreType")
                        .WithMany("Contests")
                        .HasForeignKey("ScoreTypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", "Subject")
                        .WithMany("Contests")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Exam", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Contest", "Contest")
                        .WithMany("Exams")
                        .HasForeignKey("ContestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.ExamDetail", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Exam", "Exam")
                        .WithMany("ExamDetails")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", "Question")
                        .WithMany("ExamDetails")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Notification", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Account", "Account")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswer", "StudentAnswer")
                        .WithMany("Notifications")
                        .HasForeignKey("StudentAnswerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", "Subject")
                        .WithMany("Notifications")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.QuestionGroup", "Group")
                        .WithMany("Questions")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", "Subject")
                        .WithMany("Questions")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.Result", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Contest", "Contest")
                        .WithMany("Results")
                        .HasForeignKey("ContestID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Exam", "Exam")
                        .WithMany("Results")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswer", "StudentAnswer")
                        .WithMany("Results")
                        .HasForeignKey("StudentAnswerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", "Subject")
                        .WithMany("Results")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Account", "Account")
                        .WithMany("Results")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.ScoreType", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", "Subject")
                        .WithMany("ScoreTypes")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswer", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Exam", "Exam")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Account", "Account")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswerDetail", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Answer", "Answer")
                        .WithMany("StudentAnswerDetails")
                        .HasForeignKey("AnswerID");

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Question", "Question")
                        .WithMany("StudentAnswerDetails")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.StudentAnswer", "StudentAnswer")
                        .WithMany("StudentAnswerDetails")
                        .HasForeignKey("StudentAnswerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.SubjectAccount", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Class", null)
                        .WithMany("SubjectAccounts")
                        .HasForeignKey("ClassID");

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Subject", "Subject")
                        .WithMany("SubjectAccounts")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Account", "Account")
                        .WithMany("SubjectAccounts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongQuanLyCongTacKhaoThi.Data.Entities.TeacherContest", b =>
                {
                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Contest", "Contest")
                        .WithMany("TeacherContests")
                        .HasForeignKey("ContestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyCongTacKhaoThi.Data.Entities.Account", "Teacher")
                        .WithMany("TeacherContests")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
